def galactic_calculator(a, b, operation):
    if operation == 'add':
        return a + b
    elif operation == 'subtract':
        return a - b
    elif operation == 'power':
        return a ** b
    elif operation == 'modulus':
        return a % b